### ISSUE TITLE
bootstrap: "mtimestore -A" to store file's MIN(mtime, author-date).

### ISSUE THREAD

**Issue by sto6** [kareltucek/git-mtime-extension#2]
For bootstrapping, each file's original-mtime was lost (of commits before this extension was in place). Yet we have two pieces of knowledge constraining it:

original-mtime <= current-mtime
original-mtime <= commit-time

**Comment by kareltucek** [comment]
True, but I do not like the idea of constraining them because:

1) 'save all' is meant to save the current repository state as it is and leave full responsibility up to the user. I believe that this is the conceptually correct behaviour in situations in which the motivation of use is not clearly given. Adding it would force an assumption on other people's workflow.

2) I do not see any reason why we should try to 'guess' something which is not correct anyway. Since the user most likely needs exact and correct times , I think we can assume he has a way of obtaining them (e.g., another non-git repository or working tree). I think we can assume that since using commit times (as discussed in the original discussion on http://stackoverflow.com/questions/1964470/whats-the-equivalent-of-use-commit-times-for-git) solves the problem much more elegantly.

3) Commit times and modification times seem to me as a pretty unrelated functionality. I do not see a reason why someone interested in modification times should want commit times.

4) I don't know of a fast way of computing commit times. There had been serious performance issues with the bash driven version under cygwin. Since the c++ version aims to be usable even on windows, this means a problem.

If there are good reasons for this, anyone is welcome to fork and tailor for his needs.

**Comment by sto6** [comment]
Very well, valid points. I'll respond anyway. And thanks for your git extension.

Clear to me there are both camps, folks that: _settle_ for author-date (or commit-time) as a poor alternative, despite wanting mtime; versus those that want exactly commit-time.

"constrain", "force": My poor initial conception of the request. Agreed, keep user choice AND zero impact to existing usage model:

mtimestore -A (new option, to keep -a as-is; and use author-date not commit-time) would provide this new feature. User can CHOOSE to exploit it (therefore also choosing to pay the one-time extra run-time) or not. Recall Linus's mtime-feature objection was all about his single (make) usage model, not willing to give the user a usage model choice.

Agreed possibly other  author-date (or commit-time) solutions can be exploited (prior to user's one-time: mtimestore -a). But it presupposes a good one exists that does so conditionally; my initial review says they don't yet. i.e. Don't touch a file with mtime already older than the author-date. Agreed one of those can be tweaked to do it conditionally; but someone will be first with an integrated solution, and this "best of both work-arounds" would set a new standard... ;)

**Comment by kareltucek** [comment]
I am terribly sorry for so late response (I had totally forgotten this email). 

My conclusion is that adding the author-date of the last change won't do much harm (is it the use case you are aiming for?). Still, I am afraid I have no idea how to compute this efficiently, so only the bash version will get this functionality atm.
